add get punto de reciclaje
circle-8/backend pull request #16
Opened 2023-07-15 18:15 UTC by maikgiordano98

2023-07-15 20:13 UTC, germanalopez commented on src/main/java/org/circle8/controller/request/punto_reciclaje/PuntoReciclajeRequest.java
> +		if(id != null && recicladorId == null)
Revisar esta validacion con GET /puntos_reciclaje. 
Este filtro tambien se usa para ese endpoint y este no requiere el id.

2023-07-15 20:17 UTC, germanalopez commented on src/main/java/org/circle8/service/PuntoReciclajeService.java
> +	public PuntoReciclaje get(PuntoReciclajeFilter filter) throws ServiceError{
El service tiene que devolver un objeto tipo DTO

2023-07-15 20:26 UTC, germanalopez commented on src/main/java/org/circle8/controller/request/punto_reciclaje/PuntoReciclajeRequest.java
> +		this.recicladorId = parseLong(queryParams, "id_reciclador");
Si se cambio el nombre del parametro en el codigo, cambiarlo en la documentacion tambien: https://github.com/circle-8/docs/blob/master/API.md#get-puntos_reciclaje

2023-07-16 01:39 UTC, maikgiordano98 commented on src/main/java/org/circle8/controller/request/punto_reciclaje/PuntoReciclajeRequest.java
> +		this.recicladorId = parseLong(queryParams, "id_reciclador");
lo di vuelta por como esta en el router, creo que lo mejor seria dejarlo como reciclador_id y darlo vuelta en el router.

2023-07-16 01:39 UTC, maikgiordano98 commented on src/main/java/org/circle8/service/PuntoReciclajeService.java
> +	public PuntoReciclaje get(PuntoReciclajeFilter filter) throws ServiceError{
done

2023-07-16 01:40 UTC, maikgiordano98 commented on src/main/java/org/circle8/controller/request/punto_reciclaje/PuntoReciclajeRequest.java
> +		if(id != null && recicladorId == null)
no se me ocurre como hacer. Pense en crear un validationGet en la interfaz e implementarlo, que opinas de eso @NewtonGauss ?

2023-07-16 15:53 UTC, NewtonGauss commented on src/main/java/org/circle8/controller/request/punto_reciclaje/PuntoReciclajeRequest.java
> +		if(id != null && recicladorId == null)
creemos otra `Request`, son dos distintas. `PuntoReciclajeRequest` y `PuntoReciclajeGetRequest` ponele
Despues con el codigo duplicado podemos ver de armar algo que lo unifique

2023-07-16 15:55 UTC, NewtonGauss commented on src/main/java/org/circle8/controller/request/punto_reciclaje/PuntoReciclajeRequest.java
> +		this.recicladorId = parseLong(queryParams, "id_reciclador");
estoy a favor de darlo vuelta en el router

2023-07-16 17:51 UTC, NewtonGauss commented on src/main/java/org/circle8/controller/request/punto_reciclaje/PuntoReciclajeRequest.java
> +		if(id != null && recicladorId == null)
Es mas, pensandolo bien, para que necesita `Request`? Si no recibe query parameters

2023-07-17 23:58 UTC, NewtonGauss requested changes

2023-07-17 23:58 UTC, NewtonGauss commented on src/main/java/org/circle8/controller/PuntoReciclajeController.java
> +			}
Pongamos esto fuera del try

2023-07-17 23:58 UTC, NewtonGauss commented on src/main/java/org/circle8/controller/PuntoReciclajeController.java
> +			}
Si puede ser NotFound, entonces el `Dao` deberia manejar esto devolviendo un `Optional` y luego usar el `NotFoundException` en el service. Porque sino se me ocurre que incluso el `toResponse` puede explotar.
Podes verlo en este PR #17

2023-07-17 23:58 UTC, NewtonGauss commented on src/main/java/org/circle8/dao/PuntoReciclajeDao.java
> +		}
Guarda con correr el formatter sobre codigo que no se toca. Aparecen estas lineas en el commit que no tienen nada que ver

2023-07-17 23:58 UTC, NewtonGauss commented on src/main/java/org/circle8/dao/PuntoReciclajeDao.java
> +			try (var rs = select.executeQuery()) {
pongamos este `try` dentro del anterior:
`try (var t = open(true); var select = createSelectForGet(t, id, recicladorId); var rs = select.executeQuery())`

2023-07-17 23:58 UTC, NewtonGauss commented on src/main/java/org/circle8/dao/PuntoReciclajeDao.java
> +		while (rs.next()) {
No es un while, es un if

2023-07-17 23:58 UTC, NewtonGauss commented on src/main/java/org/circle8/dao/PuntoReciclajeDao.java
> +		b.append("\n AND pr.\"CiudadanoId\" = " + recicladorId);
No usemos los parametros asi, hay que usar los parametros del `PreparedStatement` (los que se ponen como `?`).
Si bien es dudoso que justo nos vengan a meter un SQL Injection, tambien nos ahorramos tener que hacer esto a mano.

2023-07-17 23:58 UTC, NewtonGauss commented on src/main/java/org/circle8/dao/PuntoReciclajeDao.java
> +		b.append("\n AND pr.\"CiudadanoId\" = " + recicladorId);
Ademas... si siempre se va a hacer `append` sobre `b`, entonces estas dos lineas pueden ir tranquilamente en `SELECT_GET`

2023-07-17 23:58 UTC, NewtonGauss commented on src/main/java/org/circle8/route/Routes.java
> +			.post("/reciclador/{reciclador_id}/punto_reciclaje/{id}/notificacion/{id_residuo}", result(puntoReciclajeController::notificacion))
Esto se cambio aca, pero no se cambio en `ID_RECICLADOR_PARAM`

2023-07-17 23:58 UTC, NewtonGauss commented on src/main/java/org/circle8/service/PuntoReciclajeService.java
> +			return PuntoReciclajeDto.from(this.dao.get(id, recicladorId));
Aca es donde yo incluiria el `Optional`. Fijate el PR #17

2023-07-18 21:26 UTC, maikgiordano98 commented on src/main/java/org/circle8/dao/PuntoReciclajeDao.java
> +		}
désolé pretier

2023-07-18 21:33 UTC, maikgiordano98 commented on src/main/java/org/circle8/dao/PuntoReciclajeDao.java
> +		b.append("\n AND pr.\"CiudadanoId\" = " + recicladorId);
lo cambie a como estaba antes, no entendi como hacerlo respecto a este comment

Ademas... si siempre se va a hacer append sobre b, entonces estas dos lineas pueden ir tranquilamente en SELECT_GET

2023-07-18 21:47 UTC, maikgiordano98 commented on src/main/java/org/circle8/dao/PuntoReciclajeDao.java
> +		b.append("\n AND pr.\"CiudadanoId\" = " + recicladorId);
ya lo entendi, creo haberlo hecho

2023-07-18 21:48 UTC, maikgiordano98 commented on src/main/java/org/circle8/service/PuntoReciclajeService.java
> +			return PuntoReciclajeDto.from(this.dao.get(id, recicladorId));
lo hice disinto devuelvo el optional en el dao, lo agarro ahi y tiro excepcion  q capturo en el controller, avisame si te gusta! :)

2023-07-19 23:41 UTC, NewtonGauss commented on src/main/java/org/circle8/service/PuntoReciclajeService.java
> +			return PuntoReciclajeDto.from(this.dao.get(id, recicladorId));
que me pones signo de exclamacion

2023-07-19 23:56 UTC, NewtonGauss requested changes
Faltarian los tests

2023-07-19 23:56 UTC, NewtonGauss commented on src/main/java/org/circle8/controller/PuntoReciclajeController.java
> +			}
como `puntoReciclajeDto` podria ser null si `toResponse` no devuelve null

2023-07-19 23:56 UTC, NewtonGauss commented on src/main/java/org/circle8/controller/request/punto_reciclaje/PuntoReciclajeRequest.java
> +		this.recicladorId = parseLong(queryParams, "reciclador_id");
Dejale un TODO a esto que cuando mergeemos el PR de Ger deberiamos usar `Parser`

2023-07-19 23:56 UTC, NewtonGauss commented on src/main/java/org/circle8/dao/PuntoReciclajeDao.java
> +			return Optional.of(getPunto(rs));
Si `getPunto` retorna `null`, esto explota. Ponele un `Optional.ofNullable`

2023-07-19 23:56 UTC, NewtonGauss commented on src/main/java/org/circle8/dao/PuntoReciclajeDao.java
> +			p.setObject(i + 1, parameters.get(i));
No tiene sentido armar una lista siempre del mismo tamaño y luego recorrerla con un for. Directamente se puede hacer
``` java
p.setLong(1, id);
p.setLong(2, recicladorId);
```

2023-07-19 23:56 UTC, NewtonGauss commented on src/main/java/org/circle8/dao/PuntoReciclajeDao.java
> +		var b = new StringBuilder(SELECT_GET);
Al pedo usar un `StringBuilder` si voy a usar el String pelado. Directamente pasale `SELECT_GET` a `prepareStatement`

2023-07-19 23:56 UTC, NewtonGauss commented on src/main/java/org/circle8/dao/PuntoReciclajeDao.java
> +		    	AND pr."CiudadanoId" = ?
Hay una combinacion de tabs y espacios que me esta rompiendo los ojos.
```suggestion
		SELECT pr."ID", pr."Titulo", pr."Latitud", pr."Longitud", pr."DiasAbierto", pr."CiudadanoId" , prtr."TipoResiduoId", tr."Nombre", ciu."UsuarioId"
		  FROM "PuntoReciclaje" AS pr
		  LEFT JOIN "PuntoReciclaje_TipoResiduo" AS prtr ON prtr."PuntoReciclajeId" = pr."ID"
		  LEFT JOIN "TipoResiduo" AS tr on tr."ID" = prtr."TipoResiduoId"
		  LEFT JOIN "Ciudadano" AS ciu on pr."CiudadanoId" = ciu."ID"
		 WHERE pr."ID" = ?
		   AND pr."CiudadanoId" = ?
```

2023-07-19 23:56 UTC, NewtonGauss commented on src/main/java/org/circle8/service/PuntoReciclajeService.java
> +				orElseThrow(() -> new NotFoundException("No existe el punto de reciclaje")));
Te paso una version mas bonita (porque lo digo yo :hear_no_evil:)
```suggestion
			return this.dao.get(id, recicladorId)
				.map(PuntoReciclajeDto::from)
				.orElseThrow(() -> new NotFoundException("No existe el punto de reciclaje"));
```

2023-07-19 23:56 UTC, NewtonGauss commented on src/main/java/org/circle8/service/PuntoReciclajeService.java
> +	public PuntoReciclajeDto get(Long id, Long recicladorId) throws ServiceError, NotFoundException {
```suggestion
	public PuntoReciclajeDto get(Long id, Long recicladorId) throws ServiceException {
```

2023-07-19 23:56 UTC, NewtonGauss commented on src/main/java/org/circle8/controller/PuntoReciclajeController.java
> +		}
relacionado a un comentario del service: aca agregar un ultimo catch que catchee `ServiceException` (luego del catch de `NotFoundException` y `ServiceError`. Que tenga
```
return new ErrorResponse(ErrorCode.BAD_REQUEST, e.getMessage(), e.getDevMessage());
```

2023-07-19 23:56 UTC, NewtonGauss commented on src/main/java/org/circle8/controller/PuntoReciclajeController.java
> +		} catch ( NotFoundException e ) {
Si me pones un catch con espacios adelante y atras, hace que el otro sea igual che...

2023-07-20 17:05 UTC, NewtonGauss commented on src/test/java/org/circle8/integration/PuntoReciclajeGetTest.java
> +			.body("id", equalTo(1))
aca estaria bueno sumar un par de validaciones mas sobre el body, no solo ID... a criterio del dev

2023-07-20 17:05 UTC, NewtonGauss approved these changes
Lo veo bien. No lo mergeemos directo en develop, sino que mergealo en el que estas trabajando del POST

2023-07-21 21:26 UTC, merged