Feat/post put delete punto reciclaje
circle-8/backend pull request #19
Opened 2023-07-17 22:37 UTC by maikgiordano98

2023-07-18 00:57 UTC, NewtonGauss commented
Tene en cuenta los comentarios puestos sobre #18

2023-07-20 00:28 UTC, NewtonGauss requested changes
Tambien faltan tests

2023-07-20 00:28 UTC, NewtonGauss commented on package-lock.json
Que es este package-lock???

2023-07-20 00:28 UTC, NewtonGauss commented on src/main/java/org/circle8/controller/PuntoReciclajeController.java
> +		}
Aplicar cambios sobre esto cuando se arreglen en el otro PR

2023-07-20 00:28 UTC, NewtonGauss commented on src/main/java/org/circle8/controller/PuntoReciclajeController.java
> +				return new SuccessResponse("El punto se actualizo con exito.");
Esto esta mal. Segun la [docu de la API](https://github.com/circle-8/docs/blob/master/API.md#general):

> Todo PUT y POST retorna lo mismo que su GET respectivo.

2023-07-20 00:28 UTC, NewtonGauss commented on src/main/java/org/circle8/controller/request/punto_reciclaje/PuntoReciclajeRequest.java
> +	}
Esto esta mal: si se requiere una validacion distinta, es porque entonces es otra request distinta y no deberia usar el mismo `Request`. No ahorremos en archivos, es al pedo...

Despues nos va a pasar que queremos meter un cambio en un lado y termina llegando un bug por el otro.

2023-07-20 00:28 UTC, NewtonGauss commented on src/main/java/org/circle8/controller/request/punto_reciclaje/PuntoReciclajeRequest.java
> +			.toList();
si no se manda `tipos_residuo` como Integer esto rompe y no da un mensaje bonito y entendible. Hay que rodearlo de un try-catch para `NumberFormatException`

2023-07-20 00:28 UTC, NewtonGauss commented on src/main/java/org/circle8/controller/request/punto_reciclaje/PuntoReciclajeRequest.java
> +	public Long recicladorId;  //TODO: cómo se obtiene el valor de {reciclador_id} para el POST
1. Va en la URL
2. No deberia ser este request el del POST

2023-07-20 00:28 UTC, NewtonGauss commented on src/main/java/org/circle8/service/PuntoReciclajeService.java
> +	public boolean put(Long id, Long recicladorId, PuntoReciclajeRequest req) throws ServiceError{
No deberia ser un `boolean`, deberia devolver el PuntoReciclaje actualizado, dado que se requiere para la response.

2023-07-20 00:28 UTC, NewtonGauss commented on src/main/java/org/circle8/service/PuntoReciclajeService.java
> +	public boolean delete(Long id, Long recicladorId) throws ServiceError {
No deberia devolver boolean. No le pregunte si puede o no borrar, sino que directamente le ordeno a la funcion que lo haga.
Si quiero decir que puede ser que no lo borré por que no lo encontré, en ese caso se puede usar la exception de not found que es más acorde.

2023-07-20 00:28 UTC, NewtonGauss commented on src/main/java/org/circle8/service/PuntoReciclajeService.java
> +		} catch (PersistenceException | SQLException e) {
`SQLException` jamas tiene que llegar al Service

2023-07-20 00:28 UTC, NewtonGauss commented on src/main/java/org/circle8/service/PuntoReciclajeService.java
> +		} catch (PersistenceException | SQLException e) {
`SQLException` jamas tiene que llegar al Service

2023-07-20 00:28 UTC, NewtonGauss commented on src/main/java/org/circle8/controller/PuntoReciclajeController.java
>  			}
no tiene sentido que DELETE devuelva un mensaje. Con que retorne 200 es suficiente.

2023-07-20 00:28 UTC, NewtonGauss commented on src/main/java/org/circle8/dao/PuntoReciclajeDao.java
> +		""";
No se usa

2023-07-20 00:28 UTC, NewtonGauss commented on src/main/java/org/circle8/dao/PuntoReciclajeDao.java
> +		""";
no se usa

2023-07-20 00:28 UTC, NewtonGauss commented on src/main/java/org/circle8/dao/PuntoReciclajeDao.java
> +  		""";
Tienen mezcla de espacios y tabs
```suggestion
		INSERT INTO public."PuntoReciclaje"("CiudadanoId", "Latitud", "Longitud", "DiasAbierto", "Titulo")
		VALUES (?, ?, ?, ?, ?)
		""";
```

2023-07-20 00:28 UTC, NewtonGauss commented on src/main/java/org/circle8/dao/PuntoReciclajeDao.java
> +		""";
Mezcla espacios y tabs
```suggestion
		SELECT pr."ID", pr."Titulo", pr."Latitud", pr."Longitud", pr."DiasAbierto", pr."CiudadanoId" , prtr."TipoResiduoId", tr."Nombre", ciu."UsuarioId"
		  FROM "PuntoReciclaje" AS pr
		  LEFT JOIN "PuntoReciclaje_TipoResiduo" AS prtr ON prtr."PuntoReciclajeId" = pr."ID"
		  LEFT JOIN "TipoResiduo" AS tr on tr."ID" = prtr."TipoResiduoId"
		  LEFT JOIN "Ciudadano" AS ciu on pr."CiudadanoId" = ciu."ID"
		 WHERE pr."ID" = ?
		   AND pr."CiudadanoId" = ?
		""";
```

2023-07-20 00:28 UTC, NewtonGauss commented on src/main/java/org/circle8/dao/PuntoReciclajeDao.java
>  	private static final String WHERE_CIUDADADO_NULL = """
CIUDADADO en vez de CIUDADANO

2023-07-20 00:28 UTC, NewtonGauss commented on src/main/java/org/circle8/dao/PuntoReciclajeDao.java
>  	private static final String WHERE_CIUDADADO_NOT_NULL = """
CIUDADADO en vez de CIUDADANO
![image](https://github.com/circle-8/backend/assets/58175814/5975e538-b428-4c77-9a5b-64a904ff9013)

2023-07-20 00:28 UTC, NewtonGauss commented on src/main/java/org/circle8/dao/PuntoReciclajeDao.java
> +		""";
```suggestion
		INSERT INTO public."PuntoReciclaje_TipoResiduo"("PuntoReciclajeId", "TipoResiduoId")
		VALUES (?, ?);
		""";
```

2023-07-20 00:28 UTC, NewtonGauss commented on src/main/java/org/circle8/dao/PuntoReciclajeDao.java
> +		""";
```suggestion
		DELETE FROM public."PuntoReciclaje" AS pr
		 WHERE pr."ID" = ?
		   AND pr."CiudadanoId" = ?
		""";
```

2023-07-20 00:28 UTC, NewtonGauss commented on src/main/java/org/circle8/dao/PuntoReciclajeDao.java
> +		""";
```suggestion
		DELETE FROM public."PuntoReciclaje_TipoResiduo" AS r
		 WHERE r."PuntoReciclajeId" = ?
		""";
```

2023-07-20 00:28 UTC, NewtonGauss commented on src/main/java/org/circle8/dao/PuntoReciclajeDao.java
> +		""";
```suggestion
		UPDATE public."PuntoReciclaje"
		SET
		""";
```

2023-07-20 00:28 UTC, NewtonGauss commented on src/main/java/org/circle8/dao/PuntoReciclajeDao.java
> +		""";
Ademas, que es este `SET` vacio? Si vamos a usar formato, usemos %s y luego un `String.format`

2023-07-20 00:28 UTC, NewtonGauss commented on src/main/java/org/circle8/dao/PuntoReciclajeDao.java
> +		""";
```suggestion
		WHERE "ID" = ?
		  AND "CiudadanoId" = ?
		""";
```

2023-07-20 00:28 UTC, NewtonGauss commented on src/main/java/org/circle8/dao/PuntoReciclajeDao.java
> +	public boolean put(Transaction t, Long id, Long recicladorId, PuntoReciclajeRequest req) throws SQLException, PersistenceException {
No debe nunca hacer throw de SQLException

2023-07-20 00:28 UTC, NewtonGauss commented on src/main/java/org/circle8/dao/PuntoReciclajeDao.java
> +				return false;
esto no es un return false, esto es un error por una razon:
- No encontro lo que iba a borrar -> no es un false, es un not found

2023-07-20 00:28 UTC, NewtonGauss commented on src/main/java/org/circle8/dao/PuntoReciclajeDao.java
> +		} catch (SQLException | PersistenceException e) {
No hace falta catchear `PersistenceException`, ya lo estas throweando

2023-07-20 00:28 UTC, NewtonGauss commented on src/main/java/org/circle8/dao/PuntoReciclajeDao.java
> +		try (var update = createSelectForPut(t, id, recicladorId, req)) {
no creas un `SELECT` para un PUT, creas un `UPDATE`

2023-07-20 00:28 UTC, NewtonGauss commented on src/main/java/org/circle8/dao/PuntoReciclajeDao.java
> +	public void saveRelacion(Transaction t, long trId, long prId) throws PersistenceException {
no me gusta `saveRelacion`. No tiene nada que ver a los otros nombres, y no me indica que es lo que estoy guardando realmente.

`saveTipos` es mas adecuado

2023-07-20 00:28 UTC, NewtonGauss commented on src/main/java/org/circle8/dao/PuntoReciclajeDao.java
> +		} catch (SQLException | PersistenceException e ) {
No hace falta el catch de Persistence

2023-07-20 00:28 UTC, NewtonGauss commented on src/main/java/org/circle8/dao/PuntoReciclajeDao.java
> +			return true;
mismo comentario que mas arriba sobre el boolean

2023-07-20 00:28 UTC, NewtonGauss commented on src/main/java/org/circle8/dao/PuntoReciclajeDao.java
> +	public boolean delete(Transaction t, Long id, Long recicladorId) throws PersistenceException, SQLException {
mismo comentario que mas arriba sobre el SQLException

2023-07-20 00:28 UTC, NewtonGauss commented on src/main/java/org/circle8/dao/PuntoReciclajeDao.java
> +	public boolean deleteRelacion(Transaction t, Long id) throws PersistenceException, SQLException {
mismo comentario que mas arriba relacionado a `saveRelacion`

2023-07-20 00:28 UTC, NewtonGauss commented on src/main/java/org/circle8/dao/PuntoReciclajeDao.java
> +		}
me gusta como lo resolviste

2023-07-20 00:28 UTC, NewtonGauss commented on src/main/java/org/circle8/dao/PuntoReciclajeDao.java
> +			.append(System.lineSeparator())
`System.lineSeparator()`??? pone `"\n"`, no te me hagas el ingles ahora despues de tanto throw `SQLException`

2023-07-20 00:28 UTC, NewtonGauss commented on src/main/java/org/circle8/dto/Dia.java
> +		return respuesta.toString();
esto con `GSON.toJson` lo haces en 2 lineas y con menos chances de error

2023-07-20 00:28 UTC, NewtonGauss commented on src/main/java/org/circle8/dto/PuntoReciclajeDto.java
> +			.recicladorId(recicladorId).build();
separamelo en una linea por parametro porfis

2023-07-20 02:06 UTC, maikgiordano98 commented
Te debo los test, pero ya modifique todo acorde a lo pedido!! 
Estaria bueno mergear este pr con el otro del get, estuve tocando cosas en ambos. En este pr cambie lo del tipo residuo y modifique el metodo de ger tamb. Vamos a tener varios conflictos.

2023-07-20 16:56 UTC, NewtonGauss commented
> Te debo los test, pero ya modifique todo acorde a lo pedido!! Estaria bueno mergear este pr con el otro del get, estuve tocando cosas en ambos. En este pr cambie lo del tipo residuo y modifique el metodo de ger tamb. Vamos a tener varios conflictos.

mergeate el PR del GET aca y el otro PR cerremoslo

2023-07-20 17:01 UTC, NewtonGauss commented on src/main/java/org/circle8/dto/Dia.java
> +		return gson.toJson(diasArray);
se puede usar `GSON` (la variable de la clase) que ya existe (fijate que 10 lineas mas arriba se usa)

2023-07-20 17:02 UTC, NewtonGauss commented on src/main/java/org/circle8/service/PuntoReciclajeService.java
> +			throw new ServiceError("Ha ocurrido un error al obtener el listado de puntos de reciclaje", e);
El mensaje del throw esta mal

2023-07-20 17:02 UTC, NewtonGauss commented on src/main/java/org/circle8/service/PuntoReciclajeService.java
> +			throw new ServiceError("Ha ocurrido un error al obtener el listado de puntos de reciclaje", e);
el mensaje esta mal, no es un listado

2023-07-20 17:03 UTC, NewtonGauss commented on src/main/java/org/circle8/dao/PuntoReciclajeDao.java
> +			if (delete.executeUpdate() <= 0 )
le dejas un TODO aca? Quiero probar una cosa despues

2023-07-20 17:13 UTC, NewtonGauss requested changes

2023-07-20 17:13 UTC, NewtonGauss commented on src/main/java/org/circle8/controller/PuntoReciclajeController.java
> +		val req = new PuntoReciclajePostRequest(ctx.queryParamMap());
Los parametros para los PUT y los POST no tienen que ir como query parameters, tienen que ir como body (un json). Fijate como esta hecho para User

2023-07-24 21:57 UTC, NewtonGauss approved these changes

2023-07-24 21:57 UTC, merged