feat: first endpoint
circle-8/backend pull request #58
Opened 2023-08-01 23:01 UTC by HernanKozak

2023-08-02 00:17 UTC, NewtonGauss requested changes
- Faltan tests
- No tiene `expand`, cada consulta se trae todo. Recomiendo tomar como ejemplo `SolicitudDao`
- Quedan TODOs
- Hay que arreglar indentacion
- Dejé un par de preguntas de cosas que me llaman la atención

2023-08-02 00:17 UTC, NewtonGauss commented on src/main/java/org/circle8/controller/PuntoReciclajeController.java
> +			//TODO: Redundante y mal el nombre
Si ya tiene el TODO y se sabe que hacer, metele el fix nomas

2023-08-02 00:17 UTC, NewtonGauss commented on src/main/java/org/circle8/controller/TransaccionController.java
> +	private final TransaccionService service;
poner debajo de las constantes

2023-08-02 00:17 UTC, NewtonGauss commented on src/main/java/org/circle8/controller/TransaccionController.java
> +		}
se puede reemplazar todo por `catch ( ServiceException e ) { return new ErrorResponse(e); }` ver como esta en otros endpoints (relativamente nuevos)

2023-08-02 00:17 UTC, NewtonGauss commented on src/main/java/org/circle8/controller/TransaccionController.java
> +			return new ErrorResponse(ErrorCode.INTERNAL_ERROR, e.getMessage(), e.getDevMessage());
`new ErrorResponse(e)`

2023-08-02 00:17 UTC, NewtonGauss commented on src/main/java/org/circle8/controller/TransaccionController.java
> +			)*/
por que?

2023-08-02 00:17 UTC, NewtonGauss commented on src/main/java/org/circle8/controller/response/TransaccionResponse.java
> +	List<ResiduoResponse> residuos;
por que sacar el `public`?

2023-08-02 00:17 UTC, NewtonGauss commented on src/main/java/org/circle8/dao/TransaccionDao.java
> +					WHERE tr."ID" = ?
Indentar bien

2023-08-02 00:17 UTC, NewtonGauss commented on src/main/java/org/circle8/dao/TransaccionDao.java
> +		 					LEFT JOIN Public."TipoResiduo" AS tre on re."TipoResiduoId" = tre."ID"
Todo tiene que ser `LEFT`?

2023-08-02 00:17 UTC, NewtonGauss commented on src/main/java/org/circle8/dao/TransaccionDao.java
> +		 					LEFT JOIN Public."PuntoReciclaje" AS pr on tr."PuntoReciclajeId"=pr."ID"
me parece raro tanto `JOIN`. Me traigo realmente todos los datos? Incluso cuando no hay `expand`?

2023-08-02 00:17 UTC, NewtonGauss commented on src/main/java/org/circle8/dao/TransaccionDao.java
> +										rs.getBoolean("EntregaConfirmada")),
poner bien la indentacion

2023-08-02 00:17 UTC, NewtonGauss commented on src/main/java/org/circle8/dao/TransaccionDao.java
> +					new Transporte(rs.getLong("TransporteId"),
lo llena completo incluso cuando no hay `expand`? Esto no esta bien

2023-08-02 00:17 UTC, NewtonGauss commented on src/main/java/org/circle8/dao/TransaccionDao.java
> +										new Transportista(rs.getLong("UsuarioId")),
Mismo comentario que para `Transporte`

2023-08-02 00:17 UTC, NewtonGauss commented on src/main/java/org/circle8/dao/TransaccionDao.java
> +					new PuntoReciclaje(
Mismo comentario que para `Transporte`

2023-08-02 00:17 UTC, NewtonGauss commented on src/main/java/org/circle8/dao/TransaccionDao.java
> +										.build();
arreglar indentacion

2023-08-02 00:17 UTC, NewtonGauss commented on src/main/java/org/circle8/dao/TransaccionDao.java
> +					val r = Residuo.builder()
Se llena `Residuo` incluso cuando no tiene `expand`?

2023-08-02 00:17 UTC, NewtonGauss commented on src/main/java/org/circle8/dto/TransaccionDto.java
> -	public String puntoReciclajeUri;
por que?

2023-08-02 00:17 UTC, NewtonGauss commented on src/main/java/org/circle8/dto/TransaccionDto.java
> +						residuos.stream().map(ResiduoDto::toResponse).toList());
arreglar indentacion

2023-08-02 00:17 UTC, NewtonGauss commented on src/main/java/org/circle8/dto/TransaccionDto.java
> +						residuos.stream().map(ResiduoDto::toResponse).toList());
residuos no puede ser null?

2023-08-02 00:17 UTC, NewtonGauss commented on src/main/java/org/circle8/dto/TransaccionDto.java
> +						puntoReciclaje != null ? "/reciclador/" + puntoReciclaje.recicladorId + "/punto_reciclaje/" + puntoReciclaje.id : "",
si `puntoReciclaje == null` entonces deberia mandar `null` en vez de `""`

2023-08-02 00:17 UTC, NewtonGauss commented on src/main/java/org/circle8/dto/TransporteDto.java
> +		//TODO: CHEQUEAR ESTO: t.transaccionId = entity.transaccionId;
que tiene?

2023-08-02 00:17 UTC, NewtonGauss commented on src/main/java/org/circle8/dto/TransporteDto.java
> +			2L,
recordar estos TODO

2023-08-02 00:17 UTC, NewtonGauss commented on src/main/java/org/circle8/entity/Transportista.java
> -	// TODO: polyline
no hace falta para este PR

2023-08-02 00:17 UTC, NewtonGauss commented on src/main/java/org/circle8/service/TransaccionService.java
> +								.orElseThrow(() -> new NotFoundException("No existe el punto de residuos"));
arreglar indentacion

2023-08-02 00:17 UTC, NewtonGauss commented on src/main/java/org/circle8/service/TransaccionService.java
> +								.orElseThrow(() -> new NotFoundException("No existe el punto de residuos"));
"punto de residuos" o "transaccion"?

2023-08-02 00:18 UTC, NewtonGauss commented
Me falto algo mas: la idea es que los branches se llamen `feature/x`

2023-08-02 00:28 UTC, HernanKozak commented on src/main/java/org/circle8/controller/TransaccionController.java
> +			)*/
Lo había puesto cuando no tenía resulta la lógica de los residuos. Descomentado.

2023-08-02 00:29 UTC, HernanKozak commented on src/main/java/org/circle8/controller/response/TransaccionResponse.java
> +	List<ResiduoResponse> residuos;
Fue un error al descomentar.

2023-08-02 02:06 UTC, HernanKozak commented on src/main/java/org/circle8/dao/TransaccionDao.java
> +		 					LEFT JOIN Public."TipoResiduo" AS tre on re."TipoResiduoId" = tre."ID"
Al ser todos FKs de Ids entiendo que pueden ser todos JOIN comunes

2023-08-02 02:07 UTC, HernanKozak commented on src/main/java/org/circle8/dao/TransaccionDao.java
> +		 					LEFT JOIN Public."PuntoReciclaje" AS pr on tr."PuntoReciclajeId"=pr."ID"
Cuando no hay expand algunos no son necesarios. Por mí lo mantengo así, si no puedo hacer que se pregunte por el expand previo a pegarle a la base y que haya varios select dependiendo

2023-08-02 02:18 UTC, HernanKozak commented on src/main/java/org/circle8/dto/TransaccionDto.java
> -	public String puntoReciclajeUri;
Error, entiendo. Agregado nuevamente.

2023-08-02 02:24 UTC, HernanKozak commented on src/main/java/org/circle8/dto/TransaccionDto.java
> +						puntoReciclaje != null ? "/reciclador/" + puntoReciclaje.recicladorId + "/punto_reciclaje/" + puntoReciclaje.id : "",
Modificado para transporte y reciclador:

Lo había copiado de acá:
	public PuntoReciclajeResponse toResponse() {
		return new PuntoReciclajeResponse(
			id,
			titulo,
			latitud,
			longitud,
			dias.stream().map(DiaResponse::from).toList(),
			tipoResiduo.stream().map(TipoResiduoDto::toResponse).toList(),
			reciclador != null ? "/user/" + reciclador.id : "",
			recicladorId,
			reciclador != null ? reciclador.toResponse() : null
		);
	}

2023-08-02 02:24 UTC, HernanKozak commented on src/main/java/org/circle8/dto/TransporteDto.java
> +		//TODO: CHEQUEAR ESTO: t.transaccionId = entity.transaccionId;
Era para mí,  para recordar de preguntar si era correcto que esté el transaccionId ahí. Quitado

2023-08-02 02:33 UTC, HernanKozak commented on src/main/java/org/circle8/service/TransaccionService.java
> +								.orElseThrow(() -> new NotFoundException("No existe el punto de residuos"));
Depende del punto de vista. Si se lo mira como un log que oriente, Transaccion, si se apunta a meterle confusión y mística al código puede ser tanto "punto de residuos" como muchas otras cosas.

2023-08-02 17:47 UTC, germanalopez commented on src/main/java/org/circle8/dto/TransporteDto.java
> +		return new TransporteResponse(
Te dejo el comentario aca porque no me deja en el otro metodo. En el From entity hay que validar primero si el entity que llega por parametro es null. Si lo es retornar null. Esto evita un nullpointer en el metodo. Ver en solicitudDto y agregarlo en este dto

2023-08-02 17:48 UTC, germanalopez commented on src/main/java/org/circle8/dto/TransportistaDto.java
> +		//TODO: implementar
Mismo comentario de from entity que en transporteDto

2023-08-02 17:51 UTC, germanalopez commented on src/main/java/org/circle8/dao/TransaccionDao.java
> +			SELECT tr."ID", tr."FechaPrimerContacto", tr."FechaEfectiva", tr."PuntoReciclajeId", tr."TransporteId",
Esto hay que separarlo en en select simple y select puntuales para los expand. Despues se usa un metodo createSelect tanto para el GET y el LIST y ahi valida segun filtro y expand como armar la consulta. La diferencia principal entre uno y otro es el where id = ?.
Podes tomar de ejemplo SolicitudDao y ZonaDao

2023-08-04 00:06 UTC, NewtonGauss commented on src/test/java/org/circle8/integration/transaccion/TransaccionGetTest.java
> +}
habria que validar un poco mas, no solo el status. Si hago `transaccion/1` realmente me devuelve la transaccion 1?

Y los expands? no se testean?

Recomiendo correr los tests con la cobertura para ver cuanto codigo se cubre

2023-08-09 19:23 UTC, germanalopez commented on src/main/java/org/circle8/controller/request/transaccion/TransaccionPutRequest.java
> +	public Transaccion toEntity() {
Esto tiene que estar en el DTO

2023-08-09 19:27 UTC, germanalopez commented on src/main/java/org/circle8/service/TransaccionService.java
> +		try (var t = dao.open()){
aca se puede usar dao.open(true), eso hace que haga el autocommit por lo que no hace falta hacerlo abajo

2023-08-09 19:30 UTC, germanalopez commented on src/main/java/org/circle8/service/TransaccionService.java
> +			dao.put(t, id, req.toEntity());
Aca como comente antes, deberia recibir el dto, que previamente se creo desde el request, y hacer el toEntity

2023-08-09 19:36 UTC, germanalopez commented on src/main/java/org/circle8/controller/TransaccionController.java
> +			throw new RuntimeException(e);
ServiceException se supone que se lanza cuando hay algun error por algun dato mal en el request.
En el catch hay que tirar: return new ErrorResponse(e);
Esa lanza un 400

2023-08-15 21:46 UTC, NewtonGauss commented
hay que resolver los conflictos con develop

2023-08-16 23:09 UTC, merged