Feature/put user
circle-8/backend pull request #77
Opened 2023-08-24 20:08 UTC by germanalopez

2023-08-28 21:40 UTC, NewtonGauss requested changes

2023-08-28 21:40 UTC, NewtonGauss commented on src/main/java/org/circle8/controller/UserController.java
> +			log.error("[Request:{}] error saving new user", req, e);
```suggestion
			log.error("[Request:{}, id={}] error updating user", req, id, e);
```

2023-08-28 21:40 UTC, NewtonGauss commented on src/main/java/org/circle8/controller/UserController.java
> +			return new ErrorResponse(ErrorCode.BAD_REQUEST, e.getMessage(), e.getDevMessage());
Creo que se puede `e` y va a ser mejor
```suggestion
			return new ErrorResponse(e);
```

2023-08-28 21:40 UTC, NewtonGauss commented on src/main/java/org/circle8/controller/UserController.java
> +			return new ErrorResponse(ErrorCode.BAD_REQUEST, e.getMessage(), e.getDevMessage());
lo mismo en el catch de arriba

2023-08-28 21:40 UTC, NewtonGauss commented on src/main/java/org/circle8/controller/request/user/UserRequest.java
> +		if( organizacionId != null && (tipoUsuario == null || !List.of(TipoUsuarioResponse.RECICLADOR_URBANO, TipoUsuarioResponse.ORGANIZACION).contains(tipoUsuario)))
si sacas el espacio al final, sacaselo al principio tambien. Preferiria que no se lo saques igual 👓

2023-08-28 21:40 UTC, NewtonGauss commented on src/main/java/org/circle8/dao/OrganizacionDao.java
> +	public void put(Transaction t, User u) throws PersistenceException, NotFoundException {
en vez de `put` que sea `update`, pues para el dao estas haciendo una actualizacion

2023-08-28 21:40 UTC, NewtonGauss commented on src/main/java/org/circle8/dao/RecicladorUrbanoDao.java
> +	public void put(Transaction t, User u) throws PersistenceException, NotFoundException {
igual que para organizacion, que sea un `update`

2023-08-28 21:40 UTC, NewtonGauss commented on src/main/java/org/circle8/dao/RecicladorUrbanoDao.java
> +				put.setNull(2, Types.BIGINT);
podes hacer `put.setObject` que hace lo mismo

2023-08-28 21:40 UTC, NewtonGauss commented on src/main/java/org/circle8/dao/RecicladorUrbanoDao.java
> +			if(u.zonaId != null)
si el `PUT` del usuario no tiene `zonaId` no significa que quiero borrarle la zona, sino que significa que _no_ quiero actualizar la zona. Esto está mal

2023-08-28 21:40 UTC, NewtonGauss commented on src/main/java/org/circle8/dao/OrganizacionDao.java
> +			put.setLong(3, u.id);
el usuario puede querer actualizar solo la `razonSocial`, y en ese caso el resto va a venir en `NULL`. Pero no quiero que queden en NULL los campos de la DB

2023-08-28 21:40 UTC, NewtonGauss commented on src/main/java/org/circle8/dao/TransportistaDao.java
> +		}
esto se puede hacer con `appendCondition` de `Dao`?

2023-08-28 21:40 UTC, NewtonGauss commented on src/main/java/org/circle8/dao/TransportistaDao.java
> +		return l;
esto no estaba en otro lado?

2023-08-28 21:40 UTC, NewtonGauss commented on src/main/java/org/circle8/dao/UserDao.java
> +			put.setLong(6, user.id);
lo mismo que puse en los otros `PUT`. Puede que una request _solo_ actualice _un_ valor, y los otros vengan en NULL. Que no significa que deberian ponerse en NULL el resto

2023-08-28 21:40 UTC, NewtonGauss commented on src/main/java/org/circle8/service/RecicladorUrbanoService.java
> +	public User save(Transaction t, User u) throws ServiceException {
no deberia tener este `public`, no deberia usarse fuera del package `service`

2023-08-28 21:40 UTC, NewtonGauss commented on src/main/java/org/circle8/service/TransportistaService.java
> +	public Transportista save(Transaction t, Long userId) throws ServiceException {
no deberia tener este `public`, no deberia usarse fuera del package `service`

2023-08-28 21:40 UTC, NewtonGauss commented on src/main/java/org/circle8/service/TransportistaService.java
> +	public Optional<Transportista> getByUsuarioId(Transaction t, Long userId) throws PersistenceException {
no deberia tener este `public`, no deberia usarse fuera del package `service`

2023-08-29 16:57 UTC, germanalopez commented on src/main/java/org/circle8/dao/RecicladorUrbanoDao.java
> +			if(u.zonaId != null)
Ok, lo cambie para que si no viene la zona no haga el update

2023-08-29 16:58 UTC, germanalopez commented on src/main/java/org/circle8/dao/OrganizacionDao.java
> +			put.setLong(3, u.id);
Aca solo se esta actualizando la razonSocial, los otros 2 parametros los uso en el WHERE para saber que registro actualizar

2023-08-29 16:59 UTC, germanalopez commented on src/main/java/org/circle8/dao/TransportistaDao.java
> +		return l;
Si, lo movi a utils de puntos que despues en otro PR voy a agregar mas cosas

2023-08-29 17:00 UTC, germanalopez commented on src/main/java/org/circle8/dao/UserDao.java
> +			put.setLong(6, user.id);
No puede que dar ninguno en null xq UserRequest valida todos los datos obligatorios
Del front me va venir el formulario completo o solo los datos que se actualizaron?

2023-08-29 17:06 UTC, germanalopez commented on src/main/java/org/circle8/dao/TransportistaDao.java
> +		}
Si, ahi lo cambie por eso

2023-08-31 21:30 UTC, merged